schema_version: 1

context:
  version: "8.0.2"

package:
  name: fastapi-guard
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastapi-guard/fastapi_guard-${{ version }}.tar.gz
  sha256: 4f1b862dd95b902c0fd5bbce8caa6fb33d18d0deb3dbd391111c5cddb26a8e84

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi >=0.109.0
    - guard-core >=4.0.0
    - starlette >=0.35.0
    - uvicorn

tests:
  - python:
      imports:
        - guard
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A security library for FastAPI to control IPs, log requests, and detect penetration attempts.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rennf93/fastapi-guard

extra:
  recipe-maintainers:
    - thewchan
