schema_version: 1

context:
  version: "7.8.2"

package:
  name: fastapi-guard
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastapi-guard/fastapi_guard-${{ version }}.tar.gz
  sha256: ed891b19fc3a1278b113264eea0dffe2b9f7163971f39368af7a260ada070c88

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi
    - guard-core
    - starlette
    - uvicorn

tests:
  - python:
      imports:
        - guard
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A security library for FastAPI to control IPs, log requests, and detect penetration attempts.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rennf93/fastapi-guard

extra:
  recipe-maintainers:
    - thewchan
