schema_version: 1

context:
  version: "7.3.0"

package:
  name: fastapi-guard
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastapi-guard/fastapi_guard-${{ version }}.tar.gz
  sha256: 02edc798a7b6acedacd9fc7e18ed1bc921401522a0685182bc364b73fabcc078

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi
    - guard-core
    - starlette
    - uvicorn

tests:
  - python:
      imports:
        - guard
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A security library for FastAPI to control IPs, log requests, and detect penetration attempts.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rennf93/fastapi-guard

extra:
  recipe-maintainers:
    - thewchan
